/**
 * SMS Fusion API
 * This is the SMS Fusion API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@smsfusion.com.au
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SmsFusionApi) {
      root.SmsFusionApi = {};
    }
    root.SmsFusionApi.SMSResult = factory(root.SmsFusionApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SMSResult model module.
   * @module model/SMSResult
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SMSResult</code>.
   * @alias module:model/SMSResult
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>SMSResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SMSResult} obj Optional instance to populate.
   * @return {module:model/SMSResult} The populated <code>SMSResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('success')) {
        obj['success'] = ApiClient.convertToType(data['success'], 'Number');
      }
      if (data.hasOwnProperty('cost')) {
        obj['cost'] = ApiClient.convertToType(data['cost'], 'Number');
      }
      if (data.hasOwnProperty('count')) {
        obj['count'] = ApiClient.convertToType(data['count'], 'Number');
      }
      if (data.hasOwnProperty('failure')) {
        obj['failure'] = ApiClient.convertToType(data['failure'], ['String']);
      }
    }
    return obj;
  }

  /**
   * Unique ID for response
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Count of queued SMS
   * @member {Number} success
   */
  exports.prototype['success'] = undefined;
  /**
   * Cost of the SMS
   * @member {Number} cost
   */
  exports.prototype['cost'] = undefined;
  /**
   * Total count of SMS queued
   * @member {Number} count
   */
  exports.prototype['count'] = undefined;
  /**
   * List of failed numbers
   * @member {Array.<String>} failure
   */
  exports.prototype['failure'] = undefined;



  return exports;
}));


