/**
 * SMS Fusion API
 * This is the SMS Fusion API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@smsfusion.com.au
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/HLRCallback', 'model/HLRError', 'model/HLRResult', 'model/OutOfCredit'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/HLRCallback'), require('../model/HLRError'), require('../model/HLRResult'), require('../model/OutOfCredit'));
  } else {
    // Browser globals (root is window)
    if (!root.SmsFusionApi) {
      root.SmsFusionApi = {};
    }
    root.SmsFusionApi.DefaultApi = factory(root.SmsFusionApi.ApiClient, root.SmsFusionApi.HLRCallback, root.SmsFusionApi.HLRError, root.SmsFusionApi.HLRResult, root.SmsFusionApi.OutOfCredit);
  }
}(this, function(ApiClient, HLRCallback, HLRError, HLRResult, OutOfCredit) {
  'use strict';

  /**
   * Default service.
   * @module api/DefaultApi
   * @version 1.0.0
   */

  /**
   * Constructs a new DefaultApi. 
   * @alias module:api/DefaultApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getHLR operation.
     * @callback module:api/DefaultApi~getHLRCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HLRCallback} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * HLR number lookup
     * Perform HLR on number
     * @param {String} key API Key as generated from the &lt;a href&#x3D;&#39;https://www.smsfusion.com.au/admin/api/&#39;&gt;admin panel&lt;/a&gt;
     * @param {String} num A single phone number or &lt;a href&#x3D;&#39;https://www.smsfusion.com.au/help/msisdn/&#39;&gt;MSDISDN&lt;/a&gt;
     * @param {Object} opts Optional parameters
     * @param {String} opts.cc 2 character country code &lt;a href&#x3D;&#39;https://en.wikipedia.org/wiki/ISO_3166-2&#39;&gt;ISO 3166-2&lt;/a&gt; for formatting local numbers internationally
     * @param {module:api/DefaultApi~getHLRCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/HLRCallback}
     */
    this.getHLR = function(key, num, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'key' is set
      if (key == undefined || key == null) {
        throw new Error("Missing the required parameter 'key' when calling getHLR");
      }

      // verify the required parameter 'num' is set
      if (num == undefined || num == null) {
        throw new Error("Missing the required parameter 'num' when calling getHLR");
      }


      var pathParams = {
      };
      var queryParams = {
        'key': key,
        'num': num,
        'cc': opts['cc']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = HLRCallback;

      return this.apiClient.callApi(
        '/hlr/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getHLRCallback operation.
     * @callback module:api/DefaultApi~getHLRCallbackCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HLRResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * HLR number lookup with results going to a callback URL
     * Perform HLR on number with the result being sent to the callback URL provided
     * @param {String} key API Key as generated from the &lt;a href&#x3D;&#39;https://www.smsfusion.com.au/admin/api/&#39;&gt;admin panel&lt;/a&gt;
     * @param {Array.<String>} num Comma separated list of phone numbers or &lt;a href&#x3D;&#39;https://www.smsfusion.com.au/help/msisdn/&#39;&gt;MSDISDN&lt;/a&gt;&#39;s
     * @param {String} cb HTTP or HTTPS callback URL for each result. The result will be sent as POST with a json object included in &lt;b&gt;result&lt;/b&gt;. Timeout for callbacks is set to 30 seconds
     * @param {Object} opts Optional parameters
     * @param {String} opts.cc 2 character country code &lt;a href&#x3D;&#39;https://en.wikipedia.org/wiki/ISO_3166-2&#39;&gt;ISO 3166-2&lt;/a&gt; for formatting local numbers internationally
     * @param {module:api/DefaultApi~getHLRCallbackCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/HLRResult}
     */
    this.getHLRCallback = function(key, num, cb, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'key' is set
      if (key == undefined || key == null) {
        throw new Error("Missing the required parameter 'key' when calling getHLRCallback");
      }

      // verify the required parameter 'num' is set
      if (num == undefined || num == null) {
        throw new Error("Missing the required parameter 'num' when calling getHLRCallback");
      }

      // verify the required parameter 'cb' is set
      if (cb == undefined || cb == null) {
        throw new Error("Missing the required parameter 'cb' when calling getHLRCallback");
      }


      var pathParams = {
      };
      var queryParams = {
        'key': key,
        'num': this.apiClient.buildCollectionParam(num, 'csv'),
        'cb': cb,
        'cc': opts['cc']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = HLRResult;

      return this.apiClient.callApi(
        '/hlr-callback/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
